### ISSUE TITLE
Add some sort of obstruction test before swinging out the servo kickstand arm

### ISSUE THREAD

**Issue by jimmyli97** [RMRobotics/FTC_5421_2014-2015#47]
With the addition of the metal arm on the servo that is meant to kick the kickstand out, we now have a very long lever on our robot. We should definitely have some sort of obstruction test (maybe with ultrasonic?) before swinging this thing out

**Comment by TheAlchenmist** [comment]
This shouldn't be an issue anymore with the new design of the robot we aren't going to a kickstand arm but it could become a good idea for the tube grabbing arms.

**Comment by TheAlchenmist** [comment]
This shouldn't be an issue anymore with the new design of the robot we aren't going to a kickstand arm but it could become a good idea for the tube grabbing arms.

**Comment by TheAlchenmist** [comment]
This shouldn't be an issue anymore with the new design of the robot we aren't going to a kickstand arm but it could become a good idea for the tube grabbing arms.
