### ISSUE TITLE
Preset heights for the lift and bucket

### ISSUE THREAD

**Issue by TheAlchenmist** [RMRobotics/FTC_5421_2014-2015#65]
Should we have preset heights for each of the goals. So a preset height to be able to dump balls into the 30, 60, 90 and 120 cm goals. This would decrease the margin of error it would take on the driver. But this would require more testing to be done and a lot of testing for this to work. Also we would need to set another timer for the lift and bucket, using up all of our timers.

**Comment by jimmyli97** [comment]
Yep this would be fine - the encoder works for the lift though, so we don't
need a timer for it. We can just use an encoder limit check.
