### ISSUE TITLE
Including #pragma config

### ISSUE THREAD

**Issue by jimmyli97** [RMRobotics/FTC_5421_2014-2015#8]
See if it is possible to include a .c file with all pragma configurations (makes it so that we only have to change them in one place).

It probably isn't possible (Xander says you should just put them in each .c file), but it's so annoying I sort of want to check :)

Suggestions include:
-Changing Motor.h into Motor.c. All motor assignments should only be done in Motor.h, so in theory the pragmas are only need there
-Creating a Setup.c that only has pragmas and then including that file

**Comment by TheAlchenmist** [comment]
IT WORKS!!!!!!!!!!
